const TEXTS = {
  header: {
    getStarted: "Սկսել",
    profile: "Իմ պրոֆիլը",
    changePassword: "Փոխել գաղտնաբառը",
    subscription: "Բաժանորդագրություն",
    logout: "Ելք",
  },
  validation: {
    required: {
      brandName: "Անունը պարտադիր է",
      headline: "Վերնագիրը պարտադիր է",
      description: "Նկարագրությունը պարտադիր է",
      industry: "Ոլորտը պարտադիր է",
      region: "Մարզը պարտադիր է",
      phone: "Հեռախոսահամարը պարտադիր է",
      email: "Էլ. փոստը պարտադիր է",
      website: "Կայքը պարտադիր է",
      serviceName: "Ծառայության անունը պարտադիր է",
      serviceDescription: "Նկարագրությունը պարտադիր է",
      productDescription: "Նկարագրությունը պարտադիր է",
      productName: "Արտադրանքի անունը պարտադիր է",
      price: "գինը պարտադիր է",
    },
    format: {
      email: "Էլ. փոստը սխալ է",
      website: "Կայքի հղումը սխալ է",
    },
  },
  login: {
    title: "Ողջույն!",
    subtitle: "Չունե՞ք հաշիվ",
    register: "Գրանցվել",
  },
  loginForm: {
    fields: {
      email: "Ձեր էլ. փոստը",
      password: "Ձեր գաղտնաբառը",
    },
    placeholders: {
      email: "name@email.com",
      password: "********",
    },
    validation: {
      emailRequired: "Էլ. փոստը պարտադիր է",
      emailInvalid: "Էլ. փոստը սխալ է",
      passwordRequired: "Գաղտնաբառը պարտադիր է",
    },
    forgot: "Վերականգնել գաղտնաբառը",
    button: "Մուտք",
  },
  forgotPassword: {
    titles: {
      step1: "Վերականգնել գաղտնաբառը",
      step3: "Ստեղծել նոր գաղտնաբառ",
    },
    descriptions: {
      step1: "Խնդրում ենք մուտքագրել ձեր էլ. փոստը, որով գրանցվել եք համակարգ",
      step2: "Մենք ուղարկել ենք կոդը ձեր էլ.փոստի հասցեին",
    },
    back: "Վերադառնալ",
    invalid: "Անվավեր մուտք",
  },
  forgotPasswordStep1: {
    field: "Ձեր էլ. փոստը",
    placeholder: "name@email.com",
    validation: {
      required: "Էլ. փոստը պարտադիր է",
      invalid: "Էլ. փոստը սխալ է",
    },
    button: "Ստանալ կոդը",
  },
  forgotPasswordStep2: {
    label: "Թվային կոդ",
    validation: {
      length: "Կոդը պետք է լինի 6 նիշ",
      required: "Թվային կոդը պարտադիր է",
    },
    confirm: "Հաստատել",
  },
  forgotPasswordStep3: {
    fields: {
      password: "Նոր գաղտնաբառը",
      passwordConfirm: "Կրկնեք նոր գաղտնաբառը",
    },
    placeholders: {
      password: "********",
      passwordConfirm: "********",
    },
    validation: {
      passwordRequired: "Գաղտնաբառը պարտադիր է",
      confirmRequired: "գաղտնաբառը պարտադիր է",
      mismatch: "Գաղտնաբառերը չեն համընկնում",
    },
    button: "Հաստատել",
  },
  register: {
    done: "Կատարված է",
    back: "Հետ",
  },
  registerStep1: {
    title: "Գրանցվել",
    subtitle: "Արդեն ունեք հաշիվ?",
    login: "Մուտք գործեք",
    fields: {
      firstName: "Ձեր անունը",
      lastName: "Ձեր ազգանունը",
      email: "Ձեր էլ. փոստը",
      password: "Ձեր գաղտնաբառը",
      passwordConfirm: "Կրկնեք գաղտնաբառը",
    },
    placeholders: {
      firstName: "John",
      lastName: "Doe",
      email: "name@email.com",
      password: "********",
      passwordConfirm: "********",
    },
    button: "Շարունակել",
    validation: {
      firstName: "Անունը պարտադիր է",
      lastName: "Ազգանունը պարտադիր է",
      emailRequired: "Էլ. փոստը պարտադիր է",
      emailInvalid: "Էլ. փոստը սխալ է",
      password: "Գաղտնաբառը պարտադիր է",
      passwordConfirm: "գաղտնաբառը պարտադիր է",
    },
  },
  registerStep2: {
    title: "Հաստատեք էլփոստի հասցեն",
    subtitle: "Մենք ուղարկել ենք կոդը ձեր էլ.փոստի հասցեին",
    label: "Թվային կոդ",
    validation: {
      required: "Կոդը պարտադիր է",
      length: "Կոդը պետք է լինի 6 նիշ",
    },
    continue: "Շարունակել",
    resend: "Կրկին ուղարկել կոդը",
    resendSuccess: "Կոդը հաջողությամբ ուղարկվեց",
  },
  registerStep3: {
    title: "Վերնագիր",
    subtitle: "Հանդիսանում եք որպես իրավաբանական անձ, թե ֆիզիկական անձ:",
    orgTypes: {
      legal: "Իրավաբանական անձ",
      physical: "Ֆիզիկական անձ",
    },
    fields: {
      tin: "ՀՎՀՀ",
      name: "Ընկերության լրիվ և ճշգրիտ անվանումը",
      address: "Ընկերության հասցեն",
      headFullName: "Ղեկավարի Անուն Ազգանուն",
    },
    placeholders: {
      tin: "ՀՎՀՀ",
      name: "Company name",
      address: "Address",
      headFullName: "Name Surname",
    },
    validation: {
      orgType: "Ընտրությունը պարտադիր է",
      tin: "ՀՎՀՀ-ն պարտադիր է",
      name: "Անունը պարտադիր է",
      address: "Հասցեն պարտադիր է",
      headFullName: "Ղեկավարի անունը պարտադիր է",
    },
    continue: "Շարունակել",
  },
  createProfile: {
    title: "Պրոֆայլի ստեղծում",
    done: "Կատարված է",
  },
  createProfileStep1: {
    uploadCover: "Ներբեռնել շապիկի նկարը",
    uploadProfile: "Ներբեռնել պրոֆայլի նկարը",
    descriptionLabel: "Կարճ նկարագրություն",
    descriptionPlaceholder: "Կարճ նկարագրություն",
    industryLabel: "Ոլորտ",
    industryPlaceholder: "Ընտրել ոլորտը",
    continue: "Շարունակել",
    skip: "Բաց թողնել",
    validation: {
      description: "Նկարագրությունը պարտադիր է",
      industry: "Ընդհանուր ոլորտ ընտրելը պարտադիր է",
    },
  },
  createProfileStep2: {
    stateLabel: "Մարզ",
    statePlaceholder: "Մարզ",
    companySizeLabel: "Աշխատակիցների քանակ",
    companySizePlaceholder: "Ընտրել աշխատակիցների քանակը",
    options: ["1-5", "5-10", "10-20", "20-50", "50-100", "100+"],
    continue: "Շարունակել",
    skip: "Բաց թողնել",
    validation: {
      state: "Մարզը պարտադիր է",
      companySize: "Company size ընտրելը պարտադիր է",
    },
  },
  profileEdit: {
    title: "Անձնական տվյալներ",
    fields: {
      brandName: "Անվանում",
      headline: "Վերնագիր",
      description: "Նկարագրություն",
      industry: "Ոլորտ",
      region: "Մարզ",
      phone: "Հեռախոսահամար",
      email: "Հանրային Էլ. փոստ",
      website: "Կայքի հղում",
    },
    placeholders: {
      brandName: "մուտքագրել Անվանումը",
      headline: "մուտքագրել Վերնագիր",
      description: "մուտքագրել Նկարագրություն",
      industry: "Ընտրել Ոլորտ",
      region: "մուտքագրել Մարզ",
      phone: "մուտքագրել Հեռախոսահամար",
      email: "մուտքագրել Էլ. փոստ",
      website: "մուտքագրել Կայքի հղում",
    },
    buttons: {
      cancel: "Չեղարկել",
      save: "Պահպանել",
    },
  },
  registerSuccess: {
    title: "Բարի գալուստ Rednet",
    description: "Տես վերջին հնարավորությունները մեր դասընթացում։",
    createProfile: "Պրոֆայլի ստեղծում",
    skip: "Բաց թողնել",
  },
  serviceModal: {
    title: {
      create: "Ստեղծել ծառայություն",
      edit: "Խմբագրել ծառայությունը",
    },
    fields: {
      name: "Ծառայության անուն",
      description: "Նկարագրություն",
      upload: "Ներբեռնել լուսանկար",
    },
    placeholders: {
      name: "Մուտքագրեք ծառայության անունը",
      description: "Մուտքագրեք նկարագրություն",
    },
    buttons: {
      cancel: "Չեղարկել",
      add: "Ավելացնել ծառայություն",
      update: "Թարմացնել ծառայությունը",
    },
  },
  productModal: {
    title: {
      create: "Ստեղծել Արտադրանք",
      edit: "Խմբագրել Արտադրանքը",
    },
    fields: {
      name: "Արտադրանքի անուն",
      description: "Նկարագրություն",
      upload: "Ներբեռնել լուսանկար",
    },
    placeholders: {
      name: "Մուտքագրեք Արտադրանքի անունը",
      description: "Մուտքագրեք նկարագրություն",
    },
    buttons: {
      cancel: "Չեղարկել",
      add: "Ավելացնել Արտադրանք",
      update: "Թարմացնել Արտադրանքը",
    },
  },
  profileInfo: {
    alt: "Օգտագործողի կողմից ընտրված պատկերը։",
    editPhoto: "Խմբագրել լուսանկարը",
    badge: "ՊԵՏՔԱ ՃՇՏԵԼ",
    region: "Մարզ",
  },
  profileAnalytics: {
    title: "Վերլուծություն",
    viewsLabel: "33 պրոֆայլի դիտում",
    viewsSubtext: "Վերջին 90 օրվա դիտումները",
  },
  profileServices: {
    title: "Ծառայություններ",
    empty: "Ծառայություններ չկան",
    seeMore: "Ցուցադրել ևս 2 ծառայություն",
    addServices: "Ավելացնել ծառայություններ",
  },
  serviceItem: {
    edit: "Խմբագրել",
    delete: "Ջնջել",
  },
  profileProducts: {
    title: "Արտադրանքներ",
    empty: "Արտադրանքներ չկան",
    seeMore: "Ցուցադրել ևս 2 Արտադրանք",
    addProduct: "Ավելացնել Արտադրանք",
  },
  productItem: {
    edit: "Խմբագրել",
    delete: "Ջնջել",
  },
  profileTenders: {
    title: "մրցույթներ",
    empty: "մրցույթներ չկան",
    seeMore: "Ցուցադրել ևս 2 մրցույթներ",
    addTender: "Ստեղծել մրցույթ",
  },
  createTender: {
    title: "Տենդերի հայտարարություն",
    done: "Կատարված է",
  },
  createTenderStep1: {
    typeLabel: "Տեսակ",
    typePlaceholder: "Ընտրել տեսակը",
    nameLabel: "Անվանում",
    namePlaceholder: "Օրինակ` գրենական պիտույքների մատակարարում",
    regionLabel: "Մարզ",
    regionPlaceholder: "Ընտրել մարզը",
    continue: "Շարունակել",
    finishesAtLabel: "Ավարտ",
    finishesAtPlaceholder: "նշել ավարտը",
    validation: {
      type: "Տեսակը պարտադիր է",
      name: "Անվանումը պարտադիր է",
      region: "Մարզը պարտադիր է",
      finishesAt: "Ավարտը պարտադիր է",
    },
  },
  createTenderStep2: {
    title: "Տենդերի Հայտարարություն",
    uploadTitle: "Կցել լուսանկարներ, այլ տեսակի փաստաթղթեր կամ ֆայլեր",
    uploadButton: "Click to Upload",
    lotNameLabel: "Չափաբաժնի անվանումը",
    lotPriceLabel: "Չափաբաժնի ստարտային գինը",
    lotDaysLabel: "Գրանցվելու օրերի քանակը",
    lotDeadlineLabel: "Մատակարարման վերջնաժամկետը",
    lotHelperText: "Նվազագույնը 3 օրվանից մինչև 40",
    addLotButton: "Ավելացնել չափաբաժին",
    seeMore: "See More",
    agreement:
      "Սույնով հաստատում եմ, որ տրամադրված ամբողջ տեղեկատվությունը համապատասխանում է իրականությանը, գիտակցում եմ, որ խարդախության կամ խաբեության դեպքում պատասխանատվություն եմ կրելու",
    continue: "Շարունակել",
    fields: {
      cpvCode: "CPV կոդ",
      name: "Ապրանքի անվանում",
      quantity: "Քանակ",
      startingPrice: "Սկզբնական գին",
      description: "Նկարագրություն",
      supplyDaysCount: "Մատակարարման օրերի քանակ",
      fileNames: "Վերբեռնել ֆայլեր այս ապրանքի համար",
      measurementUnit: "Չափման միավոր",
    },
    placeholders: {
      cpvCode: "Մուտքագրեք CPV կոդը",
      name: "ապրանքի անվանումը",
      quantity: "Քանակ",
      startingPrice: "գին",
      description: "նկարագրությունը",
      supplyDaysCount: "օրերի քանակ",
      measurementUnit: "Ընտրել Չափման միավոր",
    },
    validation: {
      lotName: "Չափաբաժնի անվանումը պարտադիր է",
      lotPrice: "Գինը պարտադիր է",
      lotDays: "Օրերի քանակը պարտադիր է",
      lotDeadline: "Վերջնաժամկետը պարտադիր է",
      agreement: "Համաձայնությունը պարտադիր է",
      cpvCode: "CPV կոդը պարտադիր է",
      name: "Ապրանքի անվանումը պարտադիր է",
      quantity: "Քանակը պարտադիր է",
      quantityMin: "Քանակը պետք է լինի առնվազն 1",
      startingPrice: "Սկզբնական գինը պարտադիր է",
      startingPriceMin: "Գինը չի կարող բացասական լինել",
      description: "Նկարագրությունը պարտադիր է",
      supplyDaysCount: "օրերի քանակը պարտադիր է",
      supplyDaysCountMin: "Օրերի քանակը պետք է լինի առնվազն 1",
    },
  },
  createTenderSuccess: {
    title: "Հայտարարությունը ստեղծված է",
    description: "Շնորհավորում ենք ձեր հայտարարությունը բարեհաջող ստեղծվել է",
    seeTender: "Տեսնել հայտարարությունը",
    addTender: "Ավելացնել հայտարարություն",
  },
  notFound: {
    title: "Էջը չի գտնվել",
    description: "Խնդրում ենք ստուգեք հղումը կամ վերադառնաք գլխավոր էջ",
    backButton: "Վերադառնալ",
    homeButton: "Գլխավոր էջ",
    helpText:
      "Եթե խնդիրը շարունակվում է, խնդրում ենք կապվեք մեր աջակցության թիմի հետ",
  },
  error: {
    title: "Ինչ-որ բան սխալ գնաց",
    description: "Մենք փորձելու ենք շուտով շտկել խնդիրը",
    homeButton: "Գլխավոր էջ",
    retryButton: "Կրկին փորձել",
    helpText:
      "Եթե խնդիրը շարունակվում է, խնդրում ենք կապվեք մեր աջակցության թիմի հետ",
  },
  tenders: {
    empty: "մրցույթը չափաբաժիններ չունի",
    backToTenders: "Back To Tenders",
    seeAll: "See all",
    lots: "չափաբաժին",
    region: "մարզ",
  },
  search: {
    placeholder: "Search",
  },
  filter: {
    industry: "Ոլորտ",
    deadline: "Deadline",
    deadlineFilter: "Deadline Filter",
    price: "Price",
    publisher: "Publisher category",
    from: "From",
    to: "To",
  },
  participateTenderLot: {
    title: "Biochemistry",
    categoryName: "Category name",
    supplyDeadline: "Մատակարարման Վերջնաժամկետը",
    auctionDays: "Աուկցիոնին գրանցվելու օրերի քանակը",
    lot: "Չափաբաժին",
    region: "Տարածաշրջան",
    timeLeft: "Time left:",
    timeLeftValue: "23h 53m 12s TO DO",
    description:
      "«Ճանապարհային դեպարտամենտ» հիմնադրամի կարիքների համար ֆինանսական աուդիտի անցկացման ծառայությունների ձեռքբերման նպատակով հայտարարված գնանշման հարցում։Հայտերի ներկայացման հրավեր ՃԴ-ԳՀԾՁԲ-2023/02,«Ճանապարհային դեպարտամենտ» հիմնադրամի կարիքների համար ֆինանսական աուդիտի անցկացման ծառայությունների ձեռքբերման նպատակով հայտարարված գնանշման հարցում։Հայտերի ներկայացման հրավեր ՃԴ-ԳՀԾՁԲ-2023/02 «Ճանապարհային դեպարտամենտ» հիմնադրամի կարիքների համար ֆինանսական աուդիտի անցկացման ծառայությունների ձեռքբերման նպատակով հայտարարված գնանշման հարցում։Հայտերի ներկայացման հրավեր ՃԴ-ԳՀԾՁԲ-2023/02 «Ճանապարհային դեպարտամենտ» հիմնադրամի կարիքների համար ֆինանսական աուդիտի անցկացման ծառայությունների ձեռքբերման նպատակով հայտարարված գնանշման հարցում։Հայտերի ներկայացման հրավեր ՃԴ-ԳՀԾՁԲ-2023/02 More",
    startingPrice: "Ստարտային գինը ",
    participate: "Մասնակցել",
    seeMore: "See More",
  },
};

export { TEXTS };
